version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
    privileged: true

  prometheus:
    image: prom/prometheus:latest
    user: "1001"
    environment:
      - PUID=1001
      - PGID=1001
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /root/promgrafnode/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/promgrafnode/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
    privileged: true

  grafana:
    image: grafana/grafana:latest
    user: "1001"
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /root/promgrafnode/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /root/promgrafnode/grafana:/var/lib/grafana
    networks:
      - monitoring
    privileged: true
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.1.51:3000
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - monitoring
    privileged: true
